name: Tests

on:
  pull_request_target:
    branches:
      - main

permissions:
  pull-requests: write
  contents: read
  actions: read

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: |
          mkdir -p test-results
          pytest --junitxml=test-results/results.xml

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results

  merge:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Auto Approve
        uses: hmarr/auto-approve-action@v3.1.0
        with:
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Pull Request Merginator
        uses: managedkaos/merge-pull-request@v2.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
